[build]
  base = "./"                          # Root of the repository
  functions = "netlify/functions"      # Directory for serverless functions
  publish = ""                         # No static assets (for API deployment)
  command = "GOOS=linux GOARCH=amd64 go build -o netlify/functions/main ./cmd/api"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/main"      # Redirect to the Go API function endpoint
  status = 200
