[build]
  base = "./"                          # Root of the repository
  functions = "netlify/functions"      # Where your Go functions are located
  publish = ""                          # No static assets
  command = ""                          # No build command for Go API


[[redirects]]
  from = "/"
  to = "/.netlify/functions/main" # Redirecting to the function endpoint
  status = 200
